export const FORUM_NODES = [

  // CENTER
  {
    id: 'forum_core',
    label: 'Forum Tier 0',
    description: 'This place needs some renovating. Unlocks the skill tree.',
    icon: 'forum_core',
    direction: null,
    parent: [],
    maxLevel: 1,
    costs: [{ crystals: 1 }],
    x: 0,
    y: 0,
  },

  // META (W)
  {
    id: 'blocks_per_tap_1',
    label: 'Blocks Per Tap',
    description: 'Have lots of blocks to burn through? Unlock the blocks per tap game setting. This upgrade increases max blocks per tap by +1 per level.',
    icon: 'blocks_per_tap',
    direction: 'W',
    parent: ['fuel_cap_1'],
    maxLevel: 4,
    costs: [
      { crystals: 20 },
      { crystals: 40 },
      { crystals: 70 },
      { crystals: 110 },
    ],
    x: 0,
  },
  // {
  //   id: 'daily_runs_1',
  //   label: 'Daily Runs I',
  //   description: 'The first run of each day refunds its fuel on completion.',
  //   icon: 'daily_runs',
  //   direction: 'W',
  //   parent: ['fuel_cap_1'],
  //   maxLevel: 1,
  //   costs: [{ crystals: 40 }],
  // },
  {
    id: 'fuel_cap_1',
    label: 'Fuel Capacity I',
    description: 'Increase maximum fuel capacity to 50.',
    direction: 'W',
    parent: ['forum_core'],
    maxLevel: 1,
    costs: [{ crystals: 5 }],
  },
  {
    id: 'fuel_cap_2',
    label: 'Fuel Capacity II',
    description: 'Increase maximum fuel capacity to 100.',
    direction: 'W',
    parent: ['fuel_cap_1'],
    maxLevel: 1,
    costs: [{ shards: 5 }],
  },
  {
    id: 'fuel_cap_3',
    label: 'Fuel Capacity III',
    description: 'Increase maximum fuel capacity to 250.',
    direction: 'W',
    parent: ['fuel_cap_2'],
    maxLevel: 1,
    costs: [{ shards: 25 }],
  },
  // {
  //   id: 'fuel_efficiency_1',
  //   label: 'Fuel Efficiency I',
  //   description: 'Materials contribute 10% more fuel.',
  //   icon: 'fuel_efficiency',
  //   direction: 'W',
  //   parent: ['fuel_cap_1'],
  //   maxLevel: 5,
  //   costs: [
  //     { crystals: 15 },
  //     { crystals: 25 },
  //     { crystals: 40 },
  //     { crystals: 60 },
  //     { crystals: 90 },
  //   ],
  // },

  // TRAVEL (N)
  {
    id: 'forum_tier_1',
    label: 'Forum Tier I',
    description: 'Restore the forum and unlock trading.',
    icon: 'forum_tier',
    direction: 'N',
    parent: ['hearts_unlock'],
    maxLevel: 1,
    costs: [{ hearts: 1 }],
    permanent: true,
  },
  {
    id: 'alnera_unlock',
    label: 'Alnera Trade Route',
    description: 'Open a trade route with Alnera.',
    icon: 'alnera',
    direction: 'N',
    parent: ['forum_tier_1'],
    maxLevel: 1,
    costs: [{ hearts: 1 }],
    permanent: true,
    y:40,
  },
  {
    id: 'axolotl_3',
    label: 'Axolotl',
    description: 'Tame a third axolotl!.',
    icon: 'axolotl',
    direction: 'N',
    parent: ['bulk_cache_open'],
    maxLevel: 1,
    costs: [{ hearts: 5 }],
    permanent: true,
    y: 40,
  },
  {
    id: 'auto_feed',
    label: 'Auto Feed',
    description: 'Unlock the axolotl auto-feed button.',
    icon: 'auto_feed',
    direction: 'N',
    parent: ['hearts_unlock'],
    maxLevel: 1,
    costs: [{ hearts: 1 }],
    permanent: true,
  },
  {
    id: 'bulk_cache_open',
    label: 'Bulk Cache Open',
    description: 'Unlock a button to open all caches at once.',
    icon: 'bulk_cache',
    direction: 'N',
    parent: ['auto_feed'],
    maxLevel: 1,
    costs: [{ hearts: 1 }],
    permanent: true,
    y: 40,
  },

  {
    id: 'crystal_multiplier_permanent',
    label: 'Global Crystal Gain',
    description: 'Permanently increase passive crystal gain by 50% per level. Survives prestige.',
    icon: 'crystal_multiplier_permanent',
    direction: 'N',
    parent: ['luck_multiplier_permanent'],
    permanent: true,
    maxLevel: 3,
    costs: [
      { hearts: 2 },
      { hearts: 4 },
      { hearts: 8 },
    ],
    y:40,
  },
  {
    id: 'luck_multiplier_permanent',
    label: 'Global Luck',
    description: 'Permanently increase all proc chances (anchor, perfect anchor, crit anchor) by +15% per level.',
    icon: 'luck_multiplier_permanent',
    direction: 'N',
    parent: ['hearts_unlock'],
    permanent: true,
    maxLevel: 3,
    costs: [
      { hearts: 2 },
      { hearts: 5 },
      { hearts: 10 },
    ],
  },

  {
    id: 'revive',
    label: 'Revive',
    description: 'Revive once per game.',
    icon: 'revive',
    direction: 'N',
    parent: ['hearts_unlock'],
    maxLevel: 1,
    costs: [{ hearts: 1 }],
    permanent: true,
  },
  {
    id: 'fuel_saver_permanent',
    label: 'Fuel Saver',
    description: 'Permanently reduce blocks consumed at the end of each run by 20% per level.',
    icon: 'fuel_saver_permanent',
    direction: 'N',
    parent: ['revive'],
    permanent: true,
    maxLevel: 3,
    costs: [
      { hearts: 3 },
      { hearts: 6 },
      { hearts: 12 },
    ],
    y: 40,
  },

  // SPEED (S)
  {
    id: 'speed_curb_1',
    label: 'Speed Curb I',
    description: 'Reduce the speed growth exponent slightly.',
    icon: 'speed_curb',
    direction: 'S',
    parent: ['forum_core'],
    maxLevel: 5,
    costs: [
      { crystals: 3 },
      { crystals: 6 },
      { crystals: 12 },
      { crystals: 18 },
      { crystals: 25 },
    ],
  },
  {
    id: 'speed_curb_2',
    label: 'Speed Curb II',
    description: 'Further reduce the speed growth exponent.',
    icon: 'speed_curb',
    direction: 'S',
    parent: ['speed_curb_1'],
    maxLevel: 5,
    costs: [
      { crystals: 30 },
      { crystals: 50 },
      { crystals: 75 },
      { crystals: 110 },
      { crystals: 160 },
    ],
  },
  {
    id: 'speed_curb_3',
    label: 'Speed Curb III',
    description: 'Further reduce the speed growth exponent.',
    icon: 'speed_curb',
    direction: 'S',
    parent: ['speed_curb_2'],
    maxLevel: 5,
    costs: [
      { crystals: 60, shards: 2 },
      { crystals: 90, shards: 4 },
      { crystals: 130, shards: 6 },
      { crystals: 180, shards: 10 },
      { crystals: 240, shards: 15 },
    ],
  },
  {
    id: 'speed_curb_4',
    label: 'Speed Curb IV',
    description: 'Further reduce the speed growth exponent.',
    icon: 'speed_curb',
    direction: 'S',
    parent: ['speed_curb_3'],
    maxLevel: 5,
    costs: [
      { crystals: 100, shards: 8 },
      { crystals: 150, shards: 12 },
      { crystals: 210, shards: 18 },
      { crystals: 280, shards: 25 },
      { crystals: 360, shards: 35 },
    ],
  },
  {
    id: 'starting_width',
    label: 'Starting Platform Width',
    description: 'Increase the width of the starting platform by 10% per level.',
    icon: 'starting_width',
    direction: 'S',
    parent: ['speed_curb_1'],
    maxLevel: 5,
    costs: [
      { crystals: 20 },
      { crystals: 35 },
      { crystals: 55 },
      { crystals: 80 },
      { crystals: 110 },
    ],
  },

  // MECHANICS (E)
  {
    id: 'perfect_placement',
    label: 'Perfect Placement',
    description: 'Good placements no longer lose any block width.',
    icon: 'perfect_placement',
    direction: 'E',
    parent: ['crystal_gain_1'],
    maxLevel: 1,
    costs: [{ crystals: 5 }],
    y: -200,
  },
  {
    id: 'perfect_threshold_1',
    label: 'Perfect Placement Threshold I',
    description: 'Increase the window for a perfect placement by 15% per level.',
    icon: 'perfect_threshold',
    direction: 'E',
    parent: ['perfect_placement'],
    maxLevel: 5,
    costs: [
      { crystals: 20 },
      { crystals: 35 },
      { crystals: 55 },
      { crystals: 80 },
      { crystals: 110 },
    ],
  },
  {
    id: 'crystal_active_gain_1',
    label: 'Crystal Active Gain I',
    description: 'Gain random amounts of bonus crystals from performing feats like perfect placements.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['perfect_placement'],
    maxLevel: 5,
    costs: [
      { crystals: 15 },
      { crystals: 25 },
      { crystals: 40 },
      { crystals: 60 },
      { crystals: 85 },
    ],
  },
  {
    id: 'crystal_active_gain_2',
    label: 'Crystal Active Gain II',
    description: 'Gain more crystals from feats like perfect placements and anchors.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['anchor_unlock'],
    maxLevel: 5,
    costs: [
      { crystals: 40, shards: 1 },
      { crystals: 65, shards: 2 },
      { crystals: 95, shards: 4 },
      { crystals: 135, shards: 7 },
      { crystals: 180, shards: 11 },
    ],
  },

  {
    id: 'anchor_unlock',
    label: 'Anchor',
    description: 'Placed blocks have a 5% chance to not lose any width.',
    icon: 'anchor',
    direction: 'E',
    parent: ['crystal_gain_1'],
    maxLevel: 1,
    costs: [{ crystals: 20 }],
    // x: -100,
    y: 150,
  },
  {
    id: 'anchor_chance_1',
    label: 'Anchor Chance I',
    description: 'Increase the base chance for anchor to proc by +5% per level.',
    icon: 'anchor_chance',
    direction: 'E',
    parent: ['anchor_unlock'],
    maxLevel: 5,
    costs: [
      { crystals: 30 },
      { crystals: 50 },
      { crystals: 80 },
      { crystals: 120 },
      { crystals: 180 },
    ],
  },
  {
    id: 'perfect_anchor',
    label: 'Perfect Anchoring',
    description: 'If anchor and perfect placement both trigger, the placed block grows instead of remaining the same size. Increase anchor chance by +10% on perfect placement.',
    icon: 'perfect_anchor',
    direction: 'E',
    parent: ['anchor_unlock', 'perfect_placement'],
    hidden_requirement: ['anchor_unlock', 'perfect_placement'],
    maxLevel: 1, 
    costs: [{ shards: 5 }],
    y: 50,
  },
  {
    id: 'perfect_anchor_chance_1',
    label: 'Perfect Anchor Chance I',
    description: 'Anchor has a +10% chance to proc per level on a perfect placement.',
    icon: 'perfect_anchor',
    direction: 'E',
    parent: ['perfect_anchor'],
    maxLevel: 5,
    costs: [
      { shards: 8 },
      { shards: 14 },
      { shards: 30 },
      { shards: 60 },
      { shards: 100 },
    ],
  },
  {
    id: 'perfect_anchor_growth_1',
    label: 'Perfect Anchor Growth I',
    description: 'Increase how much the block grows on a perfect anchor.',
    icon: 'perfect_anchor_growth',
    direction: 'E',
    parent: ['perfect_anchor'],
    maxLevel: 5,
    costs: [
      { shards: 8 },
      { shards: 14 },
      { shards: 22 },
      { shards: 32 },
      { shards: 45 },
    ],
  },

  // SCORING (E, further out)
  {
    id: 'crystal_gain_1',
    label: 'Crystal Gain I',
    description: 'Gain more prismarine crystals from building higher.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['forum_core'],
    maxLevel: 5,
    costs: [
      { crystals: 1 },
      { crystals: 5 },
      { crystals: 8 },
      { crystals: 15 },
      { crystals: 20 },
    ],
    x: 0,
    y: 0,
  },
  {
    id: 'crystal_gain_2',
    label: 'Crystal Gain II',
    description: 'Gain more crystals from building higher.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['shards_unlock'],
    maxLevel: 5,
    costs: [
      { crystals: 60, shards: 2 },
      { crystals: 80, shards: 4 },
      { crystals: 110, shards: 6 },
      { crystals: 150, shards: 10 },
      { crystals: 200, shards: 15 },
    ],
  },
  {
    id: 'crystal_gain_3',
    label: 'Crystal Gain III',
    description: 'Gain more crystals from building higher.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['crystal_gain_2'],
    maxLevel: 5,
    costs: [
      { crystals: 120, shards: 8 },
      { crystals: 170, shards: 14 },
      { crystals: 230, shards: 22 },
      { crystals: 300, shards: 32 },
      { crystals: 380, shards: 45 },
    ],
    // y: -50,
  },

  {
    id: 'shards_unlock',
    label: 'Shard Unlock',
    description: 'Gain prismarine shards from feats like perfect placements and anchors.',
    icon: 'shards_unlock',
    direction: 'E',
    parent: [ 'anchor_unlock'],
    maxLevel: 1,
    costs: [{ crystals: 30 }],
    y: 220,
    x: 0,
  },
  {
    id: 'shard_active_gain_1',
    label: 'Shard Active Gain I',
    description: 'Gain more shards from perfect placements, anchors, and crits.',
    icon: 'shard_gain',
    direction: 'E',
    parent: ['shards_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 2 },
      { shards: 6 },
      { shards: 12 },
      { shards: 24 },
      { shards: 32 },
    ],
  },
  {
    id: 'shard_active_gain_2',
    label: 'Shard Active Gain II',
    description: 'Gain even more shards from feats. Tip: bubble pops give 2x more rewards than anchors and perfect placements!',
    icon: 'shard_gain',
    direction: 'E',
    parent: ['bubble_chance_1'],
    hidden_requirement: ['shards_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 40 },
      { shards: 50 },
      { shards: 65 },
      { shards: 80 },
      { shards: 100 },
    ],
  },
  {
    id: 'shard_passive_gain_1',
    label: 'Shard Passive Gain',
    description: 'Gain a small amount of shards from tower height.',
    icon: 'shard_gain',
    direction: 'N',
    parent: ['crystal_multiplier_permanent'],
    maxLevel: 5,
    costs: [
      { hearts: 1 },
      { hearts: 2 },
      { hearts: 3 },
      { hearts: 4 },
      { hearts: 5 },
    ],
    permanent: true,
    y:40,
  },

  {
    id: 'hearts_unlock',
    label: 'Prestige Unlock',
    description: 'Unlock the ability to prestige. All upgrades connected to this one are permanent upgrades.',
    icon: 'hearts_unlock',
    direction: 'N',
    parent: ['forum_core'],
    maxLevel: 1,
    costs: [{ shards: 50 }],
    y: -110,
  },

  // BUBBLES (E, off anchor_chance_1)
  {
    id: 'bubble_unlock',
    label: 'Bubble Unlock',
    description: 'Bubbles have a 20% chance to appear on screen. Pop a bubble to perform a crit!',
    icon: 'bubble',
    direction: 'E',
    parent: ['anchor_chance_1'],
    maxLevel: 1,
    costs: [{ shards: 5 }],
  },
  {
    id: 'bubble_chance_1',
    label: 'Bubble Chance I',
    description: 'Bubbles have a +10% chance to spawn per level.',
    icon: 'bubble_chance',
    direction: 'E',
    parent: ['bubble_unlock'],
    maxLevel: 4,
    costs: [
      { shards: 8 },
      { shards: 14 },
      { shards: 22 },
      { shards: 32 },
    ],
  },
  {
    id: 'bubble_amount_1',
    label: 'Bubble Amount I',
    description: 'More bubbles can be active on screen at once. +1 per level.',
    icon: 'bubble_amount',
    direction: 'E',
    parent: ['bubble_unlock'],
    maxLevel: 3,
    costs: [
      { shards: 8 },
      { shards: 14 },
      { shards: 22 },
    ],
  },
  {
    id: 'crit_chain_1',
    label: 'Crit Chain Chance I',
    description: 'Bubbles have a better chance of spawning after another bubble is popped. +10% per level.',
    icon: 'crit_chain',
    direction: 'E',
    parent: ['bubble_unlock'],
    maxLevel: 4,
    costs: [
      { shards: 10 },
      { shards: 18 },
      { shards: 28 },
      { shards: 40 },
    ],
  },
  {
    id: 'crit_anchor_unlock',
    label: 'Critical Anchor Unlock',
    description: 'If anchor procs when a bubble is popped, the block will grow instead of retaining its size. Increase anchor chance by +10% on bubble pop.',
    icon: 'crit_anchor',
    direction: 'E',
    parent: ['bubble_unlock'],
    maxLevel: 1,
    costs: [{ shards: 15 }],
  },
  {
    id: 'crit_anchor_chance_1',
    label: 'Critical Anchor Chance I',
    description: 'Anchor has a +10% chance to proc per level when a bubble is popped.',
    icon: 'crit_anchor_chance',
    direction: 'E',
    parent: ['crit_anchor_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 12 },
      { shards: 20 },
      { shards: 32 },
      { shards: 46 },
      { shards: 64 },
    ],
  },
  {
    id: 'crit_anchor_growth_1',
    label: 'Critical Anchor Growth I',
    description: 'Increase block growth on critical anchor by a bit per level.',
    icon: 'crit_anchor_growth',
    direction: 'E',
    parent: ['crit_anchor_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 12 },
      { shards: 20 },
      { shards: 32 },
      { shards: 46 },
      { shards: 64 },
    ],
  },
]