export const FORUM_NODES = [

  // CENTER
  {
    id: 'forum_core',
    label: 'Forum Tier 0',
    description: 'This place needs some renovating. Unlocks the skill tree.',
    icon: 'forum_core',
    direction: null,
    parent: [],
    maxLevel: 1,
    costs: [{ crystals: 1 }],
    x: 0,
    y: 0,
  },

  // META (W)
  {
    id: 'blocks_per_tap_1',
    label: 'Blocks Per Tap I',
    description: 'Unlock the blocks per tap setting in the pre-game modal.',
    icon: 'blocks_per_tap',
    direction: 'W',
    parent: ['fuel_cap_1'],
    maxLevel: 1,
    costs: [{ crystals: 20 }],
    x: 0,
  },
  {
    id: 'daily_runs_1',
    label: 'Daily Runs I',
    description: 'The first run of each day refunds its fuel on completion.',
    icon: 'daily_runs',
    direction: 'W',
    parent: ['fuel_cap_1'],
    maxLevel: 1,
    costs: [{ crystals: 40 }],
  },
  {
    id: 'fuel_cap_1',
    label: 'Fuel Capacity I',
    description: 'Increase maximum fuel capacity to 50.',
    icon: 'fuel_cap',
    direction: 'W',
    parent: ['forum_core'],
    maxLevel: 1,
    costs: [{ crystals: 5 }],
  },
  {
    id: 'revive',
    label: 'Revive',
    description: 'Totem of undying: revive once per game with 50% platform size.',
    icon: 'revive',
    direction: 'W',
    parent: ['blocks_per_tap_1'],
    maxLevel: 1,
    costs: [{ crystals: 30, shards: 5 }],
  },
  {
    id: 'fuel_efficiency_1',
    label: 'Fuel Efficiency I',
    description: 'Materials contribute 10% more fuel.',
    icon: 'fuel_efficiency',
    direction: 'W',
    parent: ['fuel_cap_1'],
    maxLevel: 5,
    costs: [
      { crystals: 15 },
      { crystals: 25 },
      { crystals: 40 },
      { crystals: 60 },
      { crystals: 90 },
    ],
  },

  // TRAVEL (N)
  {
    id: 'forum_tier_1',
    label: 'Forum Tier I',
    description: 'Restore the forum to its first tier.',
    icon: 'forum_tier',
    direction: 'N',
    parent: ['forum_core'],
    maxLevel: 1,
    costs: [{ crystals: 100 }],
    y: -150,
  },
  {
    id: 'alnera_unlock',
    label: 'Alnera Trade Route',
    description: 'Open a trade route with Alnera.',
    icon: 'alnera',
    direction: 'N',
    parent: ['forum_tier_1'],
    maxLevel: 1,
    costs: [{ crystals: 20 }],
  },
  {
    id: 'axolotl_3',
    label: 'Axolotl',
    description: 'Unlock a third axolotl slot.',
    icon: 'axolotl',
    direction: 'N',
    parent: ['forum_tier_1'],
    maxLevel: 1,
    costs: [{ crystals: 30 }],
  },
  {
    id: 'auto_feed',
    label: 'Auto Feed',
    description: 'Unlock the axolotl auto-feed button.',
    icon: 'auto_feed',
    direction: 'N',
    parent: ['axolotl_3'],
    maxLevel: 1,
    costs: [{ shards: 10 }],
  },
  {
    id: 'bulk_cache_open',
    label: 'Bulk Cache Open',
    description: 'Unlock a button to open all caches at once.',
    icon: 'bulk_cache',
    direction: 'N',
    parent: ['forum_tier_1'],
    maxLevel: 1,
    costs: [{ shards: 15 }],
  },

  // SPEED (S)
  {
    id: 'speed_curb_1',
    label: 'Speed Curb I',
    description: 'Reduce the speed growth exponent slightly.',
    icon: 'speed_curb',
    direction: 'S',
    parent: ['forum_core'],
    maxLevel: 5,
    costs: [
      { crystals: 3 },
      { crystals: 16 },
      { crystals: 28 },
      { crystals: 45 },
      { crystals: 70 },
    ],
  },
  {
    id: 'speed_curb_2',
    label: 'Speed Curb II',
    description: 'Further reduce the speed growth exponent.',
    icon: 'speed_curb',
    direction: 'S',
    parent: ['speed_curb_1'],
    maxLevel: 5,
    costs: [
      { crystals: 30 },
      { crystals: 50 },
      { crystals: 75 },
      { crystals: 110 },
      { crystals: 160 },
    ],
  },
  {
    id: 'speed_curb_3',
    label: 'Speed Curb III',
    description: 'Further reduce the speed growth exponent.',
    icon: 'speed_curb',
    direction: 'S',
    parent: ['speed_curb_2'],
    maxLevel: 5,
    costs: [
      { crystals: 60, shards: 2 },
      { crystals: 90, shards: 4 },
      { crystals: 130, shards: 6 },
      { crystals: 180, shards: 10 },
      { crystals: 240, shards: 15 },
    ],
  },
  {
    id: 'speed_curb_4',
    label: 'Speed Curb IV',
    description: 'Further reduce the speed growth exponent.',
    icon: 'speed_curb',
    direction: 'S',
    parent: ['speed_curb_3'],
    maxLevel: 5,
    costs: [
      { crystals: 100, shards: 8 },
      { crystals: 150, shards: 12 },
      { crystals: 210, shards: 18 },
      { crystals: 280, shards: 25 },
      { crystals: 360, shards: 35 },
    ],
  },
  {
    id: 'starting_width',
    label: 'Starting Platform Width',
    description: 'Increase the width of the starting platform.',
    icon: 'starting_width',
    direction: 'S',
    parent: ['speed_curb_1'],
    maxLevel: 5,
    costs: [
      { crystals: 20 },
      { crystals: 35 },
      { crystals: 55 },
      { crystals: 80 },
      { crystals: 110 },
    ],
  },

  // MECHANICS (E)
  {
    id: 'perfect_placement',
    label: 'Perfect Placement',
    description: 'Good placements no longer lose block width.',
    icon: 'perfect_placement',
    direction: 'E',
    parent: ['crystal_gain_1'],
    maxLevel: 1,
    costs: [{ crystals: 5 }],
    y: -200,
  },
  {
    id: 'perfect_threshold_1',
    label: 'Perfect Placement Threshold I',
    description: 'Increase the window for a perfect placement.',
    icon: 'perfect_threshold',
    direction: 'E',
    parent: ['perfect_placement'],
    maxLevel: 5,
    costs: [
      { crystals: 20 },
      { crystals: 35 },
      { crystals: 55 },
      { crystals: 80 },
      { crystals: 110 },
    ],
  },
  {
    id: 'crystal_active_gain_1',
    label: 'Crystal Active Gain I',
    description: 'Gain bonus crystals from perfect placements.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['perfect_placement'],
    maxLevel: 5,
    costs: [
      { crystals: 15 },
      { crystals: 25 },
      { crystals: 40 },
      { crystals: 60 },
      { crystals: 85 },
    ],
  },
  {
    id: 'crystal_active_gain_2',
    label: 'Crystal Active Gain II',
    description: 'Further increase bonus crystals from perfect placements and anchors.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['anchor_unlock'],
    maxLevel: 5,
    costs: [
      { crystals: 40, shards: 1 },
      { crystals: 65, shards: 2 },
      { crystals: 95, shards: 4 },
      { crystals: 135, shards: 7 },
      { crystals: 180, shards: 11 },
    ],
  },

  {
    id: 'anchor_unlock',
    label: 'Anchor Unlock',
    description: 'Small chance for a placed block to not lose any width.',
    icon: 'anchor',
    direction: 'E',
    parent: ['crystal_gain_1'],
    maxLevel: 1,
    costs: [{ crystals: 20 }],
    // x: -100,
    y: 150,
  },
  {
    id: 'anchor_chance_1',
    label: 'Anchor Chance I',
    description: 'Increase the chance for anchor to proc.',
    icon: 'anchor_chance',
    direction: 'E',
    parent: ['anchor_unlock'],
    maxLevel: 5,
    costs: [
      { crystals: 30 },
      { crystals: 50 },
      { crystals: 80 },
      { crystals: 120 },
      { crystals: 180 },
    ],
  },
  {
    id: 'perfect_anchor',
    label: 'Perfect Anchoring',
    description: 'If anchor and perfect placement both trigger, the block grows.',
    icon: 'perfect_anchor',
    direction: 'E',
    parent: ['anchor_unlock', 'perfect_placement'],
    hidden_requirements: ['anchor_unlock', 'perfect_placement'],
    maxLevel: 1, 
    costs: [{ shards: 5 }],
    y: 50,
  },
  {
    id: 'perfect_anchor_chance_1',
    label: 'Perfect Anchor Chance I',
    description: 'Increase the chance for perfect anchoring to trigger.',
    icon: 'perfect_anchor',
    direction: 'E',
    parent: ['perfect_anchor'],
    maxLevel: 5,
    costs: [
      { shards: 8 },
      { shards: 14 },
      { shards: 22 },
      { shards: 32 },
      { shards: 45 },
    ],
  },
  {
    id: 'perfect_anchor_growth_1',
    label: 'Perfect Anchor Growth I',
    description: 'Increase how much the block grows on a perfect anchor.',
    icon: 'perfect_anchor_growth',
    direction: 'E',
    parent: ['perfect_anchor'],
    maxLevel: 5,
    costs: [
      { shards: 8 },
      { shards: 14 },
      { shards: 22 },
      { shards: 32 },
      { shards: 45 },
    ],
  },

  // SCORING (E, further out)
  {
    id: 'crystal_gain_1',
    label: 'Crystal Gain I',
    description: 'Gain more prismarine crystals from tower height.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['forum_core'],
    maxLevel: 5,
    costs: [
      { crystals: 2 },
      { crystals: 5 },
      { crystals: 10 },
      { crystals: 35 },
      { crystals: 80 },
    ],
    x: 0,
    y: 0,
  },
  {
    id: 'crystal_gain_2',
    label: 'Crystal Gain II',
    description: 'Further increase crystals from tower height.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['shards_unlock'],
    maxLevel: 5,
    costs: [
      { crystals: 60, shards: 2 },
      { crystals: 80, shards: 4 },
      { crystals: 110, shards: 6 },
      { crystals: 150, shards: 10 },
      { crystals: 200, shards: 15 },
    ],
  },
  {
    id: 'crystal_gain_3',
    label: 'Crystal Gain III',
    description: 'Further increase crystals from tower height.',
    icon: 'crystal_gain',
    direction: 'E',
    parent: ['crystal_gain_2'],
    maxLevel: 5,
    costs: [
      { crystals: 120, shards: 8 },
      { crystals: 170, shards: 14 },
      { crystals: 230, shards: 22 },
      { crystals: 300, shards: 32 },
      { crystals: 380, shards: 45 },
    ],
    y: -50,
  },

  {
    id: 'shards_unlock',
    label: 'Shard Unlock',
    description: 'Unlock prismarine shards as a second currency.',
    icon: 'shards_unlock',
    direction: 'E',
    parent: [ 'anchor_unlock'],
    maxLevel: 1,
    costs: [{ crystals: 30 }],
    y: 220,
    x: 0,
  },
  {
    id: 'shard_active_gain_1',
    label: 'Shard Active Gain I',
    description: 'Gain shards from perfect placements, anchors, and crits.',
    icon: 'shard_gain',
    direction: 'E',
    parent: ['shards_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 5 },
      { shards: 10 },
      { shards: 18 },
      { shards: 28 },
      { shards: 40 },
    ],
  },
  {
    id: 'shard_active_gain_2',
    label: 'Shard Active Gain II',
    description: 'Gain shards from perfect placements, anchors, and crits.',
    icon: 'shard_gain',
    direction: 'E',
    parent: ['shard_active_gain_1'],
    maxLevel: 5,
    costs: [
      { shards: 20 },
      { shards: 35 },
      { shards: 55 },
      { shards: 80 },
      { shards: 110 },
    ],
  },
  {
    id: 'shard_passive_gain_1',
    label: 'Shard Passive Gain I',
    description: 'Gain a small amount of shards from tower height.',
    icon: 'shard_gain',
    direction: 'E',
    parent: ['hearts_unlock'],
    maxLevel: 5,
    costs: [
      { hearts: 1 },
      { hearts: 2 },
      { hearts: 3 },
      { hearts: 4 },
      { hearts: 5 },
    ],
  },

  {
    id: 'hearts_unlock',
    label: 'Heart of the Sea Unlock',
    description: 'Unlock hearts of the sea as a third currency.',
    icon: 'hearts_unlock',
    direction: 'E',
    parent: ['shard_active_gain_1'],
    maxLevel: 1,
    costs: [{ shards: 50 }],
  },

  // BUBBLES (E, off anchor_chance_1)
  {
    id: 'bubble_unlock',
    label: 'Bubble Unlock',
    description: 'Unlock critical hits. Bubbles appear on screen — place a block while one is in range to crit.',
    icon: 'bubble',
    direction: 'E',
    parent: ['anchor_chance_1'],
    maxLevel: 1,
    costs: [{ shards: 5 }],
  },
  {
    id: 'bubble_chance_1',
    label: 'Bubble Chance I',
    description: 'Increase the chance for bubbles to spawn.',
    icon: 'bubble_chance',
    direction: 'E',
    parent: ['bubble_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 8 },
      { shards: 14 },
      { shards: 22 },
      { shards: 32 },
      { shards: 45 },
    ],
  },
  {
    id: 'bubble_amount_1',
    label: 'Bubble Amount I',
    description: 'More bubbles spawn at once.',
    icon: 'bubble_amount',
    direction: 'E',
    parent: ['bubble_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 8 },
      { shards: 14 },
      { shards: 22 },
      { shards: 32 },
      { shards: 45 },
    ],
  },
  {
    id: 'crit_chain_1',
    label: 'Crit Chain Chance I',
    description: 'Increased bubble spawn chance after a critical hit.',
    icon: 'crit_chain',
    direction: 'E',
    parent: ['bubble_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 10 },
      { shards: 18 },
      { shards: 28 },
      { shards: 40 },
      { shards: 55 },
    ],
  },
  {
    id: 'crit_anchor_unlock',
    label: 'Critical Anchor Unlock',
    description: 'Anchor proc on a critical hit causes the block to grow.',
    icon: 'crit_anchor',
    direction: 'E',
    parent: ['bubble_unlock'],
    maxLevel: 1,
    costs: [{ shards: 15 }],
  },
  {
    id: 'crit_anchor_chance_1',
    label: 'Critical Anchor Chance I',
    description: 'Increase the chance for critical anchor to proc.',
    icon: 'crit_anchor_chance',
    direction: 'E',
    parent: ['crit_anchor_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 12 },
      { shards: 20 },
      { shards: 32 },
      { shards: 46 },
      { shards: 64 },
    ],
  },
  {
    id: 'crit_anchor_growth_1',
    label: 'Critical Anchor Growth I',
    description: 'Increase how much the block grows on a critical anchor.',
    icon: 'crit_anchor_growth',
    direction: 'E',
    parent: ['crit_anchor_unlock'],
    maxLevel: 5,
    costs: [
      { shards: 12 },
      { shards: 20 },
      { shards: 32 },
      { shards: 46 },
      { shards: 64 },
    ],
  },
]